version: '3'

services:
        go-dev:
                container_name: go-dev
                image: golang:latest
                working_dir: /go/src
                command: /bin/bash -c '/root/script.sh'
                tty: true
                volumes:
                        - $GIT:/go/src/
                        - $HOME/.gitconfig:/root/.gitconfig
                        - ./script.sh:/root/script.sh
                        - ./bashrc.template:/root/.bashrc
                        - ./vimrc.template:/root/.vimrc
                build:
                          context: .
                          args:
                               - http_proxy
                               - https_proxy
                               - no_proxy
    #    environment:
    #  - GOPATH=/opt/gopath
